### PR TITLE
Update to suretax 0.1.7 and support new attributes

### PR DESCRIPTION
**Pull request by arvanasse**

### CODE REVIEW

**Comment by captainbeardo** [comment]
:+1:

**Comment by dougperez** [comment]
:+1:

**Comment by arvanasse** [comment]
Merged #22

**Comment by pedromartinez** [comment]
I didn't see that we modified the value for tax amount.  Is that still going to be incorrect, or is more code coming?

**Comment by arvanasse** [comment]
@pedromartinez more code is coming.  At this point all that we're doing is passing the 'tax_on_tax' code from SureTax through to the caller.  It'll be up to atom-api (or any other user) to deal with that value as it sees fit.

**Pull request merged**
